# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fd627d879ec088d85b004924c5404ff175fb396edc8e9a24f8ab191a60afef57e134f5ec68e59965783103b84f0cbee6e4a3bf834caea5330f732108f277d50

test:
  secret_key_base: af53d812c2e7f6e1b7e9cf35cb3c4c40cc483bd2cfd1a6e95c3368d0f514211462391651bc907051acbcf503dd53278d50ecd4e1681d126763625ef31b29614c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
